# Downloads Google platform-tools (adb only) at configure time.
set(DUSTX_PT_ROOT "${CMAKE_BINARY_DIR}/platform-tools-src")
if(APPLE)
  set(DUSTX_PT_URL "https://dl.google.com/android/repository/platform-tools-latest-darwin.zip")
elseif(WIN32)
  set(DUSTX_PT_URL "https://dl.google.com/android/repository/platform-tools-latest-windows.zip")
endif()

if(DEFINED DUSTX_PT_URL)
  set(_adb "${DUSTX_PT_ROOT}/platform-tools/adb")
  set(_adb_exe "${DUSTX_PT_ROOT}/platform-tools/adb.exe")
  if(NOT EXISTS "${_adb}" AND NOT EXISTS "${_adb_exe}")
    message(STATUS "Downloading Android platform-tools for bundled adb")
    file(DOWNLOAD "${DUSTX_PT_URL}" "${CMAKE_BINARY_DIR}/platform-tools.zip"
      SHOW_PROGRESS STATUS _st TIMEOUT 180 INACTIVITY_TIMEOUT 60)
    list(GET _st 0 _code)
    if(_code EQUAL 0)
      file(ARCHIVE_EXTRACT INPUT "${CMAKE_BINARY_DIR}/platform-tools.zip" DESTINATION "${DUSTX_PT_ROOT}")
    else()
      message(WARNING "Could not download platform-tools; USB adb reverse will need a system adb")
    endif()
  endif()
  if(EXISTS "${_adb}" OR EXISTS "${_adb_exe}")
    set(DUSTX_PLATFORM_TOOLS "${DUSTX_PT_ROOT}/platform-tools" CACHE PATH "Bundled adb directory")
  endif()
endif()
